#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
  path: /api/login_check
  controller: App\Controller\UserController::loginCheckAction
  methods: [POST]

register_client:
  path: /api/register_client
  controller: App\Controller\UserController::registerClientAction
  methods: [POST]
