app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

login_check:
  path: /api/login_check
  controller: App\Controller\UserController::loginCheckAction
  methods: [POST]

register_client:
  path: /api/register
  controller: App\Controller\UserController::registerClientAction
  methods: [POST]

recharge_wallet:
  path: /api/v1/recharge_wallet
  controller: App\Controller\WalletController::rechargeWalletAction
  methods: [POST]

payment_wallet:
  path: /api/v1/payment
  controller: App\Controller\WalletController::paymentAction
  methods: [POST]

confirm_payment_wallet:
  path: /api/v1/confirm_payment
  controller: App\Controller\WalletController::confirmPaymentAction
  methods: [POST]

check_balance_wallet:
  path: /api/v1/check_balance
  controller: App\Controller\WalletController::checkBalanceAction
  methods: [POST]
  